# Generated by Django 3.0.8 on 2025-04-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='added_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Company'),
        ),
    ]
