# Generated by Django 5.2 on 2025-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20250421_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_type', models.CharField(max_length=255)),
                ('pack_quantity', models.PositiveIntegerField(help_text='e.g., how many packs like 6’s or 10’s')),
                ('qty_per_strip', models.PositiveIntegerField()),
                ('free_medicine_qty', models.PositiveIntegerField(default=0)),
                ('company_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('mrp_rate', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=10)),
                ('shop_rate', models.DecimalField(decimal_places=2, help_text='Buying price', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
