# Generated by Django 5.2 on 2025-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_purchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('cream/jel', 'Cream/Jel'), ('liquid', 'Liquid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='pack_quantity',
            field=models.PositiveIntegerField(help_text='Number of packs (e.g., 6s or 10s)'),
        ),
    ]
