# Generated by Django 5.2 on 2025-04-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_salesregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('cream/jel', 'Cream/Jel'), ('liquid', 'Liquid')], max_length=50)),
                ('pack_quantity', models.PositiveIntegerField(help_text='Number of packs (e.g., 6s or 10s)')),
                ('qty_per_strip', models.PositiveIntegerField(help_text='Number of medicines per strip')),
                ('free_medicine_qty', models.PositiveIntegerField(default=0, help_text='Loose medicines quantity')),
                ('company_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('mrp_rate', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=10)),
                ('shop_rate', models.DecimalField(decimal_places=2, help_text='Buying price', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
