# Generated by Django 5.2 on 2025-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medicinemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='loose_medicine',
            field=models.PositiveIntegerField(default=0, help_text='Loose medicines quantity'),
        ),
    ]
