# Generated by Django 5.2 on 2025-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_medicinemaster_loose_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemaster',
            name='qty_per_strip',
            field=models.FloatField(help_text='Number of medicines per strip'),
        ),
    ]
