# Generated by Django 5.2 on 2025-05-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_medicinemaster_qty_per_strip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemaster',
            name='free_medicine_qty',
        ),
    ]
