# Generated by Django 5.2 on 2025-05-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_remove_medicinemaster_free_medicine_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinemaster',
            old_name='pack_quantity',
            new_name='Number_of_medicines_per_strip',
        ),
        migrations.RenameField(
            model_name='medicinemaster',
            old_name='qty_per_strip',
            new_name='qty_in_strip',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='pack_quantity',
            new_name='Number_of_medicines_per_strip',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='qty_per_strip',
            new_name='qty_in_strip',
        ),
        migrations.RenameField(
            model_name='salesregister',
            old_name='qty_loose',
            new_name='qty_in_loose',
        ),
        migrations.RenameField(
            model_name='salesregister',
            old_name='qty_strips',
            new_name='qty_in_strips',
        ),
    ]
