# Generated by Django 5.2 on 2025-05-08 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_rename_pack_quantity_medicinemaster_number_of_medicines_per_strip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('bill_date', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=10)),
                ('cheque_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='pharmacy.bill'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('strip', 'Strip-wise'), ('unit', 'Unit-wise')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='Number_of_medicines_per_strip',
            field=models.PositiveIntegerField(blank=True, help_text='Applicable for strip-wise medicines only', null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('sachet', 'Sachet'), ('cream', 'Cream'), ('fluid', 'Fluid'), ('injection', 'Injection')], max_length=50),
        ),
    ]
