# Generated by Django 5.2 on 2025-05-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_bill1_cheque_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='batch_number',
        ),
    ]
