# Generated by Django 5.2 on 2025-05-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_remove_purchasehistory_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
