# Generated by Django 5.2 on 2025-05-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_purchasehistory_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='Number_of_medicines_per_strip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='pharmacy.bill1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='mrp_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='shop_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
