# Generated by Django 5.2 on 2025-05-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_alter_purchasehistory_number_of_medicines_per_strip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesregister',
            name='customer_mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
