# Generated by Django 5.2 on 2025-05-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_salesregister_discount_salesregister_medicine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesregister',
            old_name='qty_loose',
            new_name='qty_in_loose',
        ),
        migrations.RenameField(
            model_name='salesregister',
            old_name='qty_strips',
            new_name='qty_in_strips',
        ),
    ]
