# Generated by Django 5.2 on 2025-05-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0025_rename_qty_loose_salesregister_qty_in_loose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesregister',
            name='bill_number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
