# Generated by Django 5.2 on 2025-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0026_salesregister_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesregister',
            name='bill_number',
            field=models.CharField(max_length=100),
        ),
    ]
