# Generated by Django 5.2 on 2025-05-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0027_alter_salesregister_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('gstin', models.CharField(max_length=15)),
            ],
        ),
    ]
