# Generated by Django 5.2 on 2025-05-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0028_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill1',
            name='bill_date',
        ),
    ]
