# Generated by Django 5.2 on 2025-05-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0029_remove_bill1_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill1',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
