# Generated by Django 5.2 on 2025-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0030_bill1_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill1',
            name='bill_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
