# Generated by Django 5.2 on 2025-05-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0031_alter_bill1_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill1',
            name='combined_pay',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
