# Generated by Django 5.2 on 2025-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0032_bill1_combined_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill1',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
