# Generated by Django 5.2 on 2025-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0034_alter_bill1_combined_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=5),
        ),
    ]
