# Generated by Django 5.2 on 2025-05-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0036_medicinemaster_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemaster',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('sachet', 'Sachet'), ('cream/jel', 'Cream/Jel'), ('liquid', 'Liquid'), ('cream', 'Cream'), ('fluid', 'Fluid'), ('injection', 'Injection')], max_length=50),
        ),
    ]
