# Generated by Django 5.2 on 2025-06-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0037_alter_medicinemaster_medicine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='Number_of_medicines_per_strip',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='unit_type',
        ),
    ]
