# Generated by Django 5.2 on 2025-06-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0038_remove_purchasehistory_number_of_medicines_per_strip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemaster',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='medicinemaster',
            name='loose_medicine',
        ),
        migrations.RemoveField(
            model_name='medicinemaster',
            name='mrp_rate',
        ),
        migrations.RemoveField(
            model_name='medicinemaster',
            name='qty_in_strip',
        ),
        migrations.RemoveField(
            model_name='medicinemaster',
            name='shop_rate',
        ),
    ]
