# Generated by Django 5.2 on 2025-06-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0039_remove_medicinemaster_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemaster',
            name='company_name',
        ),
    ]
