# Generated by Django 5.2 on 2025-06-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0042_remove_medicinemaster_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemaster',
            name='total_amount',
        ),
    ]
