# Generated by Django 5.2 on 2025-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0043_remove_medicinemaster_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='qty_in_strip',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
