# Generated by Django 5.2 on 2025-06-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0044_alter_purchasehistory_qty_in_strip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='qty_in_strip',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
