# Generated by Django 5.2 on 2025-06-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0046_purchasehistory_free_medicine_qty_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='free_medicine_qty_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='qty_in_strip_history',
            field=models.IntegerField(),
        ),
    ]
